update github workflows unit_tests

diff --git a/.github/workflows/unit_tests.yml b/.github/workflows/unit_tests.yml
--- a/.github/workflows/unit_tests.yml
+++ b/.github/workflows/unit_tests.yml
@@ -60,15 +60,24 @@ jobs:
         sudo apt-get install -y docker-compose
 
     - name: Run Docker Compose Tests
-      run: docker compose -f docker-compose.test.yml up --exit-code-from opensearch_indexer_tests
+      run: |
+        docker compose -f docker-compose.test.yml up --exit-code-from access_copy_converter_tests
 
-    - name: Copy coverage file from shared volume
+    - name: Copy coverage files from shared volume
       run: |
         cp ./test_results/coverage.xml ./coverage.xml || echo "Coverage file not found"
+        cp ./test_results/coverage-access_copy_converter.xml ./coverage-access_copy_converter.xml || echo "Access copy converter coverage file not found"
 
-    - name: Upload coverage to Codecov
+    - name: Upload opensearch_indexer coverage to Codecov
       uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
       with:
         file: ./coverage.xml
+        token: ${{ secrets.CODECOV_TOKEN }}
+        slug: ${{ github.repository }}
+
+    - name: Upload access_copy_converter coverage to Codecov
+      uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
+      with:
+        file: ./coverage-access_copy_converter.xml
         token: ${{ secrets.CODECOV_TOKEN }}
         slug: ${{ github.repository }}
